routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('homepage');
Route::group([
    'namespace' => 'Frontend'
], function () {
    Route::get('/danh-sach-bai-viet', 'BlogController@index')->name('blog');
    Route::get('/chi-tiet-bai-viet-{id}', 'PostController@index')->name('post');
    Route::get('/chung-toi', 'AboutController@index')->name('about');
    Route::get('/chi-tiet-don-hang', 'TotalController@main')->name('total');
    Route::get('/yearbook', 'YearbookController@main')->name('yearbook');
});

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => 'auth',
    'as' => 'admin.'
], function () {
    Route::get('/', 'DashboardController@main')->name('dashboard');
    Route::post('posts/uploadFile', 'PostController@uploadFile')->name('posts.uploadFile');
    Route::resources(['posts' => 'PostController']);
    Route::post('slide/uploadFile', 'SlideController@uploadFile')->name('slide.uploadFile');
    Route::resources(['slide' => 'SlideController']);
    Route::post('package/uploadFile', 'PackageController@uploadFile')->name('package.uploadFile');
    Route::resources(['package' => 'PackageController']);
    Route::resources(['option' => 'OptionController']);
    Route::resources(['category-blog' => 'CategoryBlogController']);
    Route::post('member/uploadFile', 'MemberController@uploadFile')->name('member.uploadFile');
    Route::resources(['member' => 'MemberController']);
//    Route::group([
//        'prefix' => 'posts',
//        'namespace' => 'Posts'
//    ], function () {
//        Route::get('/', 'IndexController@main')->name('posts.index');
//        Route::get('/create', 'StoreController@create')->name('posts.create');
//        Route::post('/store', 'StoreController@store')->name('posts.store');
//        Route::get('/{id}', 'EditController@main')->name('posts.edit');
//        Route::post('/{id}', 'UpdateController@main')->name('posts.update');
//        Route::delete('/{id}', 'DestroyController@main')->name('posts.destroy');
//    });
});

Auth::routes();

//Route::group([
//    'namespace' => 'Auth',
//], function () {
//    Route::get('login', 'LoginController@showLoginForm')->name('login');
//    Route::post('login', 'LoginController@login')->name('login.submit');
//    Route::post('logout', 'LoginController@logout')->name('logout');
//});

//Route::get('/home', 'HomeController@index')->name('home');

app/Models/Option.php
<?php

namespace App\Models;

use App\Scopes\ActiveScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Option extends Model
{
    use SoftDeletes;


    protected $table = 'option';

    protected $fillable = [
        'name',
        'description',
        'type',
        'status',
        'user_id',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new ActiveScope());
    }
}

app/Http/Controllers/Admin/OptionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\OptionRequest;
use App\Repositories\OptionRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;

class OptionController extends Controller
{
    public $optionRepository;

    public function __construct(OptionRepository $optionRepository)
    {
        $this->optionRepository = $optionRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = $this->optionRepository->getList();
        return view('admin.option.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [];
        $optionStatus = config('const.option_status');
        $optionType = config('const.option_type');
        return view('admin.option._form', compact('data', 'optionStatus', 'optionType'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(OptionRequest $request)
    {
        $data = $request->all();
        try {
            $this->optionRepository->create($data);
            return redirect()->route('admin.option.index')->with('success', config('messages.DB_INSERT'));
        } catch (\Exception $e) {
            Log::error('Create fail !', ['error' => $e->getMessage()]);
        }
        return redirect()->back()->withInput();
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = $this->optionRepository->detail($id);
        return view('admin.option.detail', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (empty($id)){
            abort(404);
        }
        $data = $this->optionRepository->detail($id);
        $optionStatus = config('const.option_status');
        $optionType = config('const.option_type');
        return view('admin.option._form', compact('data', 'optionStatus', 'id', 'optionType'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(OptionRequest $request, $id)
    {
        $post = $request->all();
        if (empty($id) || empty($post)) {
            abort(404);
        }
        try {
            $this->optionRepository->update($id, $post);
            return redirect(route('admin.option.index'));
        } catch (\Exception $e) {
            Log::error('Update fail !', ['error' => $e->getMessage()]);
        }
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (empty($id)) {
            return $this->responErrorAjax("Xóa không thành công");
        }
        try {
            $this->optionRepository->softDelete($id);
            \request()->session()->flash('status', 'Xóa thành công!');
            return $this->responSuccessAjax(array(), "Xóa thành công");
        } catch (\Exception $e) {
            \request()->session()->flash('status', 'Xóa không thành công!');
            return $this->responErrorAjax("Xóa không thành công");
        }

    }

    public function responErrorAjax($message, $status = 400, $header = 'application/json')
    {
        $data = [
            'success' => false,
            'message' => $message
        ];
        return response($data, $status)
            ->header('Content-Type', $header);
    }

    public function responSuccessAjax($data=array(), $message, $status = 200, $header = 'application/json')
    {
        if (empty($data)){
            $data = [
                'success' => true,
                'message' => $message
            ];
        }
        return response($data, $status)
            ->header('Content-Type', $header);
    }
}

resources/views/admin/option/_form.blade.php
@extends('admin.layouts.master')

@section('content')
    <section class="breadcrumbs">
        @if(session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
    </section>
    <div class="header mt-md-5">
        <div class="page-breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/">Trang chủ</a>
                </li>
                <li><a href="{{route('admin.option.index')}}">Danh sách option</a></li>
                <li class="active">{{!empty($id) ? 'Chỉnh sửa option' : 'Tạo mới'}}</li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        <h1 class="text-left mb-5 title">{{!empty($id) ? 'Chỉnh sửa option số '.$id : 'Tạo mới option'}}</h1>
        <div class="row">
            <form id="option-add-form" method="post" class="form-horizontal"
                  action="{{!empty($id) ? route("admin.option.update",[$id]) : route("admin.option.store")}}">
                {{ csrf_field() }}
                {{ !empty($id) ? method_field('PATCH') :'' }}
                <div class="form-group">
                    <label class="col-lg-2 control-label">Tên</label>
                    <div class="col-lg-10 option-element">
                        <input type="text" class="form-control" name="name" id="option_name"
                               value="{{oldData($data,'name','')}}"
                               placeholder="Nhập tên"/>
                        @include('admin.elements.validate_error', ['message' => $errors->first('name')])
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-2 control-label">Mô tả</label>
                    <div class="col-lg-10 option-element">
                        <textarea class="form-control" name="description" id="option_description">{!!  oldData($data,'description','')!!}
                        </textarea>
                        @include('admin.elements.validate_error', ['message' => $errors->first('description')])
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-2 control-label">Thể loại<sup>*</sup></label>
                    <div class="col-lg-5 user-element">
                        <select style="width:100%;" name="type" class="form-control form-status">
                            @php($type = oldData($data, 'type', 0))
                            @foreach($optionType as $key => $value)
                                <option {{($type == $key) ? 'selected' : ''}} value="{{$key}}"/>{{$value}}
                            @endforeach
                        </select>
                        @include('admin.elements.validate_error', ['message' => $errors->first('type')])
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-2 control-label">Trạng thái<sup>*</sup></label>
                    <div class="col-lg-5 user-element">
                        <select style="width:100%;" name="status" class="form-control form-status">
                            @php($status = oldData($data, 'status', 0))
                            @foreach($optionStatus as $key => $value)
                                <option {{($status == $key) ? 'selected' : ''}} value="{{$key}}"/>{{$value}}
                            @endforeach
                        </select>
                        @include('admin.elements.validate_error', ['message' => $errors->first('status')])
                    </div>
                </div>

                <div class="form-group row" style="margin-top: 40px;">
                    <div class="col-sm-2 col-form-label"></div>
                    <div class="col-sm-10 button-submit">
                        <button class="btn btn-warning btn-reset" type="button" onclick="location.reload();">
                            Nhập lại
                        </button>
                        <button class="btn btn-success submit-option" type="submit">
                            Lưu
                        </button>
                    </div>
                </div>

            </form>
        </div>
    </div>
@endsection
@section('js')
    <script>
        CKEDITOR.replace('option_description');
    </script>
@endsection

resources/views/admin/option/detail.blade.php
@extends('admin.layouts.master')

@section('content')
    <section class="breadcrumbs">
        @if(session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
    </section>
    <div class="header mt-md-5">
        <div class="page-breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/">Trang chủ</a>
                </li>
                <li><a href="{{route('admin.option.index')}}">Danh sách option</a></li>
                <li class="active">Chi tiết option</li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        <div class="row view-notifications">
            <div class="col-lg-12 col-sm-12 col-xs-12">
                <div class="widget radius-bordered">
                    <div class="widget-header">
                        <span class="widget-caption">Chi tiết option "<strong
                                    style="color:red;">{{$data->title}}</strong>"</span>
                        <a href="{{ \Illuminate\Support\Facades\URL::previous() }}" class="btn btn-warning back-button"><i
                                    class="fa fa-reply"></i>Quay
                            lại</a>
                    </div>
                    <div class="widget-body ">

                        <table class="table table-striped table-hover table-bordered" id="option-detail">
                            <tbody>
                            @if (!empty($data))
                                <tr>
                                    <td class="detail-title">Id</td>
                                    <td>{{$data['id']}}</td>
                                </tr>
                                <tr>
                                    <td class="detail-title">Tên option</td>
                                    <td>{{$data['name']}}</td>
                                </tr>
                                <tr>
                                    <td class="detail-title">Nội dung</td>
                                    <td>{!! nl2br(e(strip_tags(html_entity_decode($data['description'])))) !!}</td>
                                </tr>
                                <tr>
                                    <td class="detail-title">Ảnh đại diện</td>
                                    <td class="avatar-detail">
                                        @if ($data['image'] =='')
                                            <img src="{{asset('/images/upload-default.png')}}">
                                        @else
                                            <img src="{{asset('/upload/option')}}/{{$data['avatar']}}">
                                        @endif
                                    </td>
                                </tr>
                                <tr>
                                    <td class="detail-title">Người tạo</td>
                                    <td>{{$data['user_name']}}</td>
                                </tr>
                                <tr>
                                    <td class="detail-title">Ngày tạo</td>
                                    <td>{{$data['created_at']}}</td>
                                </tr>
                                <tr>
                                    <td class="detail-title">Trạng thái</td>
                                    <td class="status">
                                        @if($data['status'] == config('const.status.enable'))
                                            <i class="fas fa-check-circle"></i>
                                        @else
                                            <i class="fas fa-times-circle"></i>
                                        @endif
                                    </td>
                                </tr>
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/admin/option/index.blade.php
@extends('admin.layouts.master')

@section('content')
    <section class="breadcrumbs">
        @if(session('success')) <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
    </section>
    <div class="header mt-md-5">
        <div class="page-breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/">Trang chủ</a>
                </li>
                <li><a href="{{route('admin.option.index')}}">Quản lý option</a></li>
                <li class="active">Danh sách option</li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        <h1 class="text-center mb-5 title">Danh sách option</h1>
        <div class="table-toolbar option">
            <a id="editabledatatable_new" href="{{route('admin.option.create')}}" class="btn btn-default btn-add-new">
                Thêm mới
            </a>

            <table class="table table-striped table-hover table-bordered" id="option-table">
                <thead>
                <tr role="row">
                    <th>STT</th>
                    <th>Tên option</th>
                    <th>Nội dung</th>
                    <th>Thể loại</th>
                    <th>Người tạo</th>
                    <th>Ngày tạo</th>
                    <th>Trạng thái</th>
                    <th style="display: none;"></th>
                    <th></th>
                </tr>
                </thead>

                <tbody>
                @php( $stt = 0)
                @if (!empty($data))
                    @foreach($data as $k => $row)
                        @php( $stt ++)
                        <tr class="option-{{$row->id}}">
                            <td><?php echo $stt?></td>
                            <td class="text-left"><a
                                        href="{{route('admin.option.show',['id'=> $row->id])}}">{{$row->name}}</a></td>
                            <td class="text-center">
                                {!! nl2br(e(strip_tags(html_entity_decode($row->description)))) !!}
                            </td>  <td class="text-center">
                                {{getOptionType($row->type)}}
                            </td>
                            <td class="text-left"><a
                                        href="{{route('admin.option.show',['id'=> $row->id])}}">{{$row->user_name}}</a>
                            </td>
                            <td class="text-left"><a
                                        href="{{route('admin.option.show',['id'=> $row->id])}}">{{$row->created_at}}</a>
                            </td>
                            <td class="status text-center">
                                @if($row->status==config('const.status.enable'))
                                    <a><i class="fas fa-check-circle"></i></a>
                                @else
                                    <a><i class="fas fa-times-circle"></i></a>
                                @endif
                            </td>
                            <td style="display: none;">
                                @if($row->status==config('const.status.enable'))
                                    1
                                @else
                                    0
                                @endif

                            </td>
                            <td class="action">
                                <a href="{{route('admin.option.show',['id'=> $row->id])}}"
                                   class="btn btn-success btn-xs view"><i class="fa fa-eye"></i>
                                </a>

                                <a href="{{route('admin.option.edit',['id' => $row->id])}}"
                                   class="btn btn-info btn-xs edit"><i class="fa fa-edit"></i>
                                </a>

                                <a href="javascript:showModal('{{$row->id}}')"
                                   class="btn btn-danger btn-xs delete"><i class="fa fa-trash"></i>
                                </a>
                                @include('admin.elements.modal',['modal'=>'modalConfirmDelete', 'id' => $row->id,'url' => 'option/'.$row->id,'title'=>$row->title])
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="10">Không có kết quả
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
    </div>
@endsection