routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('homepage');
Route::group([
    'namespace' => 'Frontend'
], function () {
    Route::get('/danh-sach-bai-viet', 'BlogController@index')->name('blog');
    Route::get('/chi-tiet-bai-viet-{id}', 'PostController@index')->name('post');
    Route::get('/chung-toi', 'AboutController@index')->name('about');
    Route::get('/chi-tiet-don-hang', 'TotalController@main')->name('total');
    Route::get('/yearbook', 'YearbookController@main')->name('yearbook');
});

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => 'auth',
    'as' => 'admin.'
], function () {
    Route::get('/', 'DashboardController@main')->name('dashboard');
    Route::post('posts/uploadFile', 'PostController@uploadFile')->name('posts.uploadFile');
    Route::resources(['posts' => 'PostController']);
    Route::post('slide/uploadFile', 'SlideController@uploadFile')->name('slide.uploadFile');
    Route::resources(['slide' => 'SlideController']);
    Route::post('package/uploadFile', 'PackageController@uploadFile')->name('package.uploadFile');
    Route::resources(['package' => 'PackageController']);
    Route::resources(['option' => 'OptionController']);
    Route::resources(['category-blog' => 'CategoryBlogController']);
    Route::post('member/uploadFile', 'MemberController@uploadFile')->name('member.uploadFile');
    Route::resources(['member' => 'MemberController']);
//    Route::group([
//        'prefix' => 'posts',
//        'namespace' => 'Posts'
//    ], function () {
//        Route::get('/', 'IndexController@main')->name('posts.index');
//        Route::get('/create', 'StoreController@create')->name('posts.create');
//        Route::post('/store', 'StoreController@store')->name('posts.store');
//        Route::get('/{id}', 'EditController@main')->name('posts.edit');
//        Route::post('/{id}', 'UpdateController@main')->name('posts.update');
//        Route::delete('/{id}', 'DestroyController@main')->name('posts.destroy');
//    });
});

Auth::routes();

//Route::group([
//    'namespace' => 'Auth',
//], function () {
//    Route::get('login', 'LoginController@showLoginForm')->name('login');
//    Route::post('login', 'LoginController@login')->name('login.submit');
//    Route::post('logout', 'LoginController@logout')->name('logout');
//});

//Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/layouts/header.blade.php
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Admin Memolas</title>
    <link rel="stylesheet" href="{{ secure_asset('css/app.css') }}">
    <link href="{{asset('css/admin/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('css/admin/dataTables.bootstrap.css')}}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{{ secure_asset('css/admin/style.css') }}">
    <link rel="stylesheet" href="{{ secure_asset('css/admin/main.css') }}">
    @yield('css')
    <link rel="apple-touch-icon" href="{{ secure_asset('images/logo1.png') }}">
    <link rel="shortcut icon" href="{{ secure_asset('images/logo1.png') }}">
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

    <script src="{{asset('js/admin/jquery.min.js')}}"></script>
    <script src="{{asset('js/admin/bootstrap.min.js')}}"></script>
    <script src="{{asset('js/admin/datatable/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('js/admin/datatable/ZeroClipboard.js')}}"></script>
    <script src="{{asset('js/admin/datatable/dataTables.tableTools.min.js')}}"></script>
    <script src="{{asset('js/admin/datatable/dataTables.bootstrap.min.js')}}"></script>
    <script src="{{asset('js/laroute.js')}}"></script>
    <script src="//cdn.ckeditor.com/4.8.0/full-all/ckeditor.js"></script>
    <script src="{{asset('js/admin/System.js')}}"></script>
</head>

resources/views/admin/layouts/master.blade.php
<!doctype html>
<html lang="en">
    @include('admin.layouts.header')
<body>

    @include('admin.layouts.sidebar')

    <div id="right-panel" class="right-panel">
        @include('admin.layouts.nav')
        @yield('content')
    </div>

    <script src="{{ secure_asset('js/app.js') }}"></script>
    <script src="{{ secure_asset('js/admin/sidebar.js') }}"></script>
    @yield('js')

</body>
</html>

resources/views/admin/layouts/nav.blade.php
<header id="header" class="header">
    <div class="top-left">
        <div class="navbar-header">
            <a class="navbar-brand" href="./"><img src="{{ secure_asset('images/logo.png') }}" alt="Logo"></a>
            <a class="navbar-brand hidden" href="./"><img src="{{ secure_asset('images/logo.png') }}" alt="Logo"></a>
            <a id="menuToggle" class="menutoggle"><i class="fas fa-bars"></i></a>
        </div>
    </div>
    <div class="top-right">
        <div class="header-menu">
            <div class="header-left w-100">
                <div class="form-group w-100">
                    <form class="search-form w-100 d-flex mt-2">
                        <input class="form-control rounded-0 border-right-0" type="text" placeholder="Search ..." aria-label="Search">
                        <button class="search-trigger"><i class="fa fa-search"></i></button>
                    </form>
                </div>
            </div>
            <div class="user-area dropdown float-right">
                <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="user-avatar rounded-circle" src="{{ secure_asset('images/admin.jpg') }}" alt="User Avatar">
                </a>
                <div class="user-menu dropdown-menu">
                    <a class="nav-link" href="#"><i class="fa fa-user"></i>My Profile</a>
                    <a class="nav-link" href="#"><i class="fa fa-cog"></i>Settings</a>
{{--                    <a class="nav-link" href="#"><i class="fa fa-power-off"></i>Logout</a>--}}
                    <a href="{{ route('logout') }}" class="nav-link" onclick="event.preventDefault();document.getElementById('logout-form').submit();"><i class="fa fa-power-off"></i>{{ __('Logout') }}</a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </div>
        </div>
    </div>
</header>

resources/views/admin/layouts/sidebar.blade.php
<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">
        <div id="main-menu" class="main-menu collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('admin.dashboard') }}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#sidebarPosts" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarPost">
                        <i class="menu-icon fa fa-book"></i> Quản lý bài viết
                    </a>
                    <div class="collapse" id="sidebarPosts">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item"><a class="nav-link" href="{{ route('admin.posts.index') }}">Danh sách bài viết</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ route('admin.posts.create') }}">Tạo mới</a></li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#sidebarSlide" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarSlide">
                        <i class="menu-icon fa fa-images" aria-hidden="true"></i>Quản lý slide
                    </a>
                    <div class="collapse" id="sidebarSlide">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item"><a class="nav-link" href="{{ route('admin.slide.index') }}">Danh sách slide</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ route('admin.slide.create') }}">Tạo mới</a></li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#sidebarPackage" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarPackage">
                        <i class="menu-icon fa fa-clone"></i>Quản lý gói cước
                    </a>
                    <div class="collapse" id="sidebarPackage">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item"><a class="nav-link" href="{{ route('admin.package.index') }}">Danh sách gói cước</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ route('admin.package.create') }}">Tạo mới</a></li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#sidebarOption" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarOption">
                        <i class="menu-icon fa fa-cog"></i>Quản lý option
                    </a>
                    <div class="collapse" id="sidebarOption">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item"><a class="nav-link" href="{{ route('admin.option.index') }}">Danh sách option</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ route('admin.option.create') }}">Tạo mới</a></li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#sidebarMember" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarMember">
                        <i class="menu-icon fa fa-id-card"></i>Quản lý thành viên
                    </a>
                    <div class="collapse" id="sidebarMember">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item"><a class="nav-link" href="{{ route('admin.member.index') }}">Danh sách thành viên</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ route('admin.member.create') }}">Tạo mới</a></li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#sidebarCategoryBlog" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarCategoryBlog">
                        <i class="menu-icon fa fa-id-card"></i>Quản lý loại blog
                    </a>
                    <div class="collapse" id="sidebarCategoryBlog">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item"><a class="nav-link" href="{{ route('admin.category-blog.index') }}">Danh sách loại blog</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ route('admin.category-blog.create') }}">Tạo mới</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</aside>