routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('homepage');
Route::group([
    'namespace' => 'Frontend'
], function () {
    Route::get('/danh-sach-bai-viet', 'BlogController@index')->name('blog');
    Route::get('/chi-tiet-bai-viet-{id}', 'PostController@index')->name('post');
    Route::get('/chung-toi', 'AboutController@index')->name('about');
    Route::get('/chi-tiet-don-hang', 'TotalController@main')->name('total');
    Route::get('/yearbook', 'YearbookController@main')->name('yearbook');
});

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => 'auth',
    'as' => 'admin.'
], function () {
    Route::get('/', 'DashboardController@main')->name('dashboard');
    Route::post('posts/uploadFile', 'PostController@uploadFile')->name('posts.uploadFile');
    Route::resources(['posts' => 'PostController']);
    Route::post('slide/uploadFile', 'SlideController@uploadFile')->name('slide.uploadFile');
    Route::resources(['slide' => 'SlideController']);
    Route::post('package/uploadFile', 'PackageController@uploadFile')->name('package.uploadFile');
    Route::resources(['package' => 'PackageController']);
    Route::resources(['option' => 'OptionController']);
    Route::resources(['category-blog' => 'CategoryBlogController']);
    Route::post('member/uploadFile', 'MemberController@uploadFile')->name('member.uploadFile');
    Route::resources(['member' => 'MemberController']);
//    Route::group([
//        'prefix' => 'posts',
//        'namespace' => 'Posts'
//    ], function () {
//        Route::get('/', 'IndexController@main')->name('posts.index');
//        Route::get('/create', 'StoreController@create')->name('posts.create');
//        Route::post('/store', 'StoreController@store')->name('posts.store');
//        Route::get('/{id}', 'EditController@main')->name('posts.edit');
//        Route::post('/{id}', 'UpdateController@main')->name('posts.update');
//        Route::delete('/{id}', 'DestroyController@main')->name('posts.destroy');
//    });
});

Auth::routes();

//Route::group([
//    'namespace' => 'Auth',
//], function () {
//    Route::get('login', 'LoginController@showLoginForm')->name('login');
//    Route::post('login', 'LoginController@login')->name('login.submit');
//    Route::post('logout', 'LoginController@logout')->name('logout');
//});

//Route::get('/home', 'HomeController@index')->name('home');

app/Models/Member.php
<?php

namespace App\Models;

use App\Scopes\ActiveScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Member extends Model
{
    use SoftDeletes;


    protected $table = 'member';

    protected $fillable = [
        'name',
        'job',
        'avatar',
        'infor',
        'facebook_url',
        'insta_url',
        'sort',
        'user_id',
        'status',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new ActiveScope());
    }
}

app/Http/Controllers/Admin/MemberController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\MemberRequest;
use App\Repositories\MemberRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;

class MemberController extends Controller
{
    public $memberRepository;

    public function __construct(MemberRepository $memberRepository)
    {
        $this->memberRepository = $memberRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = $this->memberRepository->getList();
        return view('admin.member.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [];
        $memberStatus = config('const.member_status');
        return view('admin.member._form', compact('data', 'memberStatus'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(MemberRequest $request)
    {
        $data = $request->all();
        try {
            $this->memberRepository->create($data);
            return redirect()->route('admin.member.index')->with('success', config('messages.DB_INSERT'));
        } catch (\Exception $e) {
            Log::error('Create fail !', ['error' => $e->getMessage()]);
        }
        return redirect()->back()->withInput();
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = $this->memberRepository->detail($id);
        return view('admin.member.detail', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (empty($id)){
            abort(404);
        }
        $data = $this->memberRepository->detail($id);
        $memberStatus = config('const.member_status');
        return view('admin.member._form', compact('data', 'memberStatus', 'id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(MemberRequest $request, $id)
    {
        $post = $request->all();
        if (empty($id) || empty($post)) {
            abort(404);
        }
        try {
            $this->memberRepository->update($id, $post);
            return redirect(route('admin.member.index'));
        } catch (\Exception $e) {
            Log::error('Update fail !', ['error' => $e->getMessage()]);
        }
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (empty($id)) {
            return $this->responErrorAjax("Xóa không thành công");
        }
        try {
            $this->memberRepository->softDelete($id);
            \request()->session()->flash('status', 'Xóa thành công!');
            return $this->responSuccessAjax(array(), "Xóa thành công");
        } catch (\Exception $e) {
            \request()->session()->flash('status', 'Xóa không thành công!');
            return $this->responErrorAjax("Xóa không thành công");
        }

    }

    public function uploadFile(Request $request)
    {
        if ($request->ajax()) {
            $sourcePath = $_FILES['fileToUpload']['tmp_name'];       // Storing source path of the file in a variable
            $targetPath = public_path() . "/upload/member";
            if (!file_exists($targetPath)) {
                if (!mkdir($targetPath, 0777, true)) {
                    echo "Check sevice! khong co quyen tao file thu muc";
                }
            }
            $nameRaw = $_FILES['fileToUpload']['name'];
            if (empty($nameRaw)){
                exit();
            }
            $nameRaw = explode('.', $nameRaw);
            $name = !empty($nameRaw[0]) ? $nameRaw[0] : '';
            $ext = !empty($nameRaw[1]) ? $nameRaw[1] : '';
            $fullName =  $name . time() . rand(1, 9999) .'.'. $ext;
            $targetPath = $targetPath . '/' . $fullName;
            if (move_uploaded_file($sourcePath, $targetPath)) {// Moving Uploaded file
                echo $fullName;
            }
        }
        exit();
    }

    public function responErrorAjax($message, $status = 400, $header = 'application/json')
    {
        $data = [
            'success' => false,
            'message' => $message
        ];
        return response($data, $status)
            ->header('Content-Type', $header);
    }

    public function responSuccessAjax($data=array(), $message, $status = 200, $header = 'application/json')
    {
        if (empty($data)){
            $data = [
                'success' => true,
                'message' => $message
            ];
        }
        return response($data, $status)
            ->header('Content-Type', $header);
    }
}

resources/views/admin/member/_form.blade.php
@extends('admin.layouts.master')

@section('content')
    <section class="breadcrumbs">
        @if(session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
    </section>
    <div class="header mt-md-5">
        <div class="page-breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/">Trang chủ</a>
                </li>
                <li><a href="{{route('admin.member.index')}}">Danh sách thành viên</a></li>
                <li class="active">{{!empty($id) ? 'Chỉnh sửa member' : 'Tạo mới'}}</li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        <h1 class="text-left mb-5 title">{{!empty($id) ? 'Chỉnh sửa thành viên số '.$id : 'Tạo mới thành viên'}}</h1>
        <div class="row">
            <form id="member-add-form" method="post" class="form-horizontal"
                  action="{{!empty($id) ? route("admin.member.update",[$id]) : route("admin.member.store")}}">
                {{ csrf_field() }}
                {{ !empty($id) ? method_field('PATCH') :'' }}
                <div class="form-group">
                    <label class="col-lg-3 control-label">Tên<sup>*</sup></label>
                    <div class="col-lg-9 member-element">
                        <input type="text" class="form-control" name="name" id="member_name"
                               value="{{oldData($data,'name','')}}"
                               placeholder="Nhập tên"/>
                        @include('admin.elements.validate_error', ['message' => $errors->first('name')])
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Thông tin</label>
                    <div class="col-lg-9 member-element">
                        <textarea class="form-control" name="infor" id="infor_description">{!!  oldData($data,'infor','')!!}
                        </textarea>
                        @include('admin.elements.validate_error', ['message' => $errors->first('infor')])
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Chức vụ<sup>*</sup></label>
                    <div class="col-lg-9 member-element">
                        <input type="text" class="form-control" name="job" id="job_name"
                               value="{{oldData($data,'job','')}}"
                               placeholder="Nhập chức vụ"/>
                        @include('admin.elements.validate_error', ['message' => $errors->first('job')])
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Link facebook</label>
                    <div class="col-lg-9 member-element">
                        <input type="text" class="form-control" name="facebook_url" id="member_facebook_url"
                               value="{{oldData($data,'facebook_url','')}}"
                               placeholder="Nhập link"/>
                        @include('admin.elements.validate_error', ['message' => $errors->first('facebook_url')])
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Link instagram</label>
                    <div class="col-lg-9 member-element">
                        <input type="text" class="form-control" name="insta_url" id="member_insta_url"
                               value="{{oldData($data,'insta_url','')}}"
                               placeholder="Nhập link"/>
                        @include('admin.elements.validate_error', ['message' => $errors->first('insta_url')])
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Thứ tự hiển thị<sup>*</sup></label>
                    <div class="col-lg-9 slide-element">
                        <input type="number" class="form-control" name="sort" id="sort_slide"
                               value="{{oldData($data,'sort','')}}"/>
                        @include('admin.elements.validate_error', ['message' => $errors->first('sort')])
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-3 control-label">Trạng thái<sup>*</sup></label>
                    <div class="col-lg-5 user-element">
                        <select style="width:100%;" name="status" class="form-control form-status">
                            @php($status = oldData($data, 'status', 0))
                            @foreach($memberStatus as $key => $value)
                                <option {{($status == $key) ? 'selected' : ''}} value="{{$key}}"/>{{$value}}</option>
                            @endforeach
                        </select>
                        @include('admin.elements.validate_error', ['message' => $errors->first('status')])
                    </div>
                </div>
                <div class="form-group upload-member">
                    <label class="col-lg-3 control-label">Ảnh đại diện<sup>*</sup></label>
                    <div class="col-lg-9 no_pad_left">
                        <div class="col-lg-4 img-member">
                            @php($avatar = oldData($data, 'avatar',''))
                            @if(empty($avatar))
                                <img src="{{asset('/images/upload-default.png')}}"
                                     id="image_url">
                            @else
                                <img src="{{asset('/upload/member/'.$avatar)}}"
                                     id="image_url">
                            @endif
                            @include('admin.elements.validate_error', ['message' => $errors->first('avatar')])
                        </div>
                        <div class="col-lg-8 notification-element">
                            <label for="post_file" class="btn btn-primary">Chọn ảnh</label>
                            <input type="file" id="post_file" name="post_file" class="upload-input"
                                   style="visibility:hidden;"/>
                            <input type="hidden" name="avatar" id="avatar" class="upload-input" value="{{$avatar}}"
                                   style="visibility:hidden;"/>

                        </div>
                    </div>
                </div>

                <div class="form-group row" style="margin-top: 40px;">
                    <div class="col-sm-3 col-form-label"></div>
                    <div class="col-sm-9 button-submit">
                        <button class="btn btn-warning btn-reset" type="button" onclick="location.reload();">
                            Nhập lại
                        </button>
                        <button class="btn btn-success submit-member" type="submit">
                            Lưu
                        </button>
                    </div>
                </div>

            </form>
        </div>
    </div>
@endsection
@php($urlUpload = !empty($id) ? '../uploadFile' : '../member/uploadFile')
@section('js')
    <script>
        $('input[type="file"]').change(function () {
            var formData = new FormData();
            var fileToUpload = $('#post_file').prop('files')[0];
            formData.append("fileToUpload", fileToUpload);
            $.ajax({
                url: '{{$urlUpload}}',
                method: 'POST',
                data: formData,
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                processData: false,
                contentType: false,
                cache: false,
                success: function (result) {
                    $('.img-member img').attr("src", "{{asset('upload/member')}}/" + result);
                    $('#avatar').val(result);
                }
            });
        });
    </script>
@endsection

resources/views/admin/member/detail.blade.php
@extends('admin.layouts.master')

@section('content')
    <section class="breadcrumbs">
        @if(session('success'))
            <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
    </section>
    <div class="header mt-md-5">
        <div class="page-breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/">Trang chủ</a>
                </li>
                <li><a href="{{route('admin.option.index')}}">Danh sách option</a></li>
                <li class="active">Chi tiết option</li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        <div class="row view-notifications">
            <div class="col-lg-12 col-sm-12 col-xs-12">
                <div class="widget radius-bordered">
                    <div class="widget-header">
                        <span class="widget-caption">Chi tiết option "<strong
                                    style="color:red;">{{$data->title}}</strong>"</span>
                        <a href="{{ \Illuminate\Support\Facades\URL::previous() }}" class="btn btn-warning back-button"><i
                                    class="fa fa-reply"></i>Quay
                            lại</a>
                    </div>
                    <div class="widget-body ">

                        <table class="table table-striped table-hover table-bordered" id="option-detail">
                            <tbody>
                            @if (!empty($data))
                                <tr>
                                    <td class="detail-title">Id</td>
                                    <td>{{$data['id']}}</td>
                                </tr>
                                <tr>
                                    <td class="detail-title">Tên option</td>
                                    <td>{{$data['name']}}</td>
                                </tr>
                                <tr>
                                    <td class="detail-title">Nội dung</td>
                                    <td>{!! nl2br(e(strip_tags(html_entity_decode($data['description'])))) !!}</td>
                                </tr>
                                <tr>
                                    <td class="detail-title">Ảnh đại diện</td>
                                    <td class="avatar-detail">
                                        @if ($data['image'] =='')
                                            <img src="{{asset('/images/upload-default.png')}}">
                                        @else
                                            <img src="{{asset('/upload/option')}}/{{$data['avatar']}}">
                                        @endif
                                    </td>
                                </tr>
                                <tr>
                                    <td class="detail-title">Người tạo</td>
                                    <td>{{$data['user_name']}}</td>
                                </tr>
                                <tr>
                                    <td class="detail-title">Ngày tạo</td>
                                    <td>{{$data['created_at']}}</td>
                                </tr>
                                <tr>
                                    <td class="detail-title">Trạng thái</td>
                                    <td class="status">
                                        @if($data['status'] == config('const.status.enable'))
                                            <i class="fas fa-check-circle"></i>
                                        @else
                                            <i class="fas fa-times-circle"></i>
                                        @endif
                                    </td>
                                </tr>
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/admin/member/index.blade.php
@extends('admin.layouts.master')

@section('content')
    <section class="breadcrumbs">
        @if(session('success')) <div class="alert alert-success" role="alert">
                {{ session('success') }}
            </div>
        @endif
    </section>
    <div class="header mt-md-5">
        <div class="page-breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="/">Trang chủ</a>
                </li>
                <li><a href="{{route('admin.member.index')}}">Quản lý thành viên</a></li>
                <li class="active">Danh sách thành viên</li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        <h1 class="text-center mb-5 title">Danh sách thành viên</h1>
        <div class="table-toolbar member">
            <a id="editabledatatable_new" href="{{route('admin.member.create')}}" class="btn btn-default btn-add-new">
                Thêm mới
            </a>

            <table class="table table-striped table-hover table-bordered" id="member-table">
                <thead>
                <tr role="row">
                    <th>STT</th>
                    <th>Avatar</th>
                    <th>Tên thành viên</th>
                    <th>Thứ tự hiển thị</th>
                    <th>Người tạo</th>
                    <th>Ngày tạo</th>
                    <th>Trạng thái</th>
                    <th style="display: none;"></th>
                    <th></th>
                </tr>
                </thead>

                <tbody>
                @php( $stt = 0)
                @if (!empty($data))
                    @foreach($data as $k => $row)
                        @php( $stt ++)
                        <tr class="member-{{$row->id}}">
                            <td><?php echo $stt?></td>
                            <td class="avatar">
                                @if ($row->avatar =='')
                                    <img src="{{asset('/images/upload-default.png')}}">
                                @else
                                    <img src="{{asset('/upload/member')}}/{{$row->avatar}}">
                                @endif
                            </td>
                            <td class="text-left"><a
                                        href="{{route('admin.member.show',['id'=> $row->id])}}">{{$row->name}}</a></td>
                            <td class="text-center">
                                {{ $row->sort }}
                            <td class="text-left"><a
                                        href="{{route('admin.member.show',['id'=> $row->id])}}">{{$row->user_name}}</a>
                            </td>
                            <td class="text-left"><a
                                        href="{{route('admin.member.show',['id'=> $row->id])}}">{{$row->created_at}}</a>
                            </td>
                            <td class="status text-center">
                                @if($row->status==config('const.status.enable'))
                                    <a><i class="fas fa-check-circle"></i></a>
                                @else
                                    <a><i class="fas fa-times-circle"></i></a>
                                @endif
                            </td>
                            <td style="display: none;">
                                @if($row->status==config('const.status.enable'))
                                    1
                                @else
                                    0
                                @endif

                            </td>
                            <td class="action">
                                <a href="{{route('admin.member.show',['id'=> $row->id])}}"
                                   class="btn btn-success btn-xs view"><i class="fa fa-eye"></i>
                                </a>

                                <a href="{{route('admin.member.edit',['id' => $row->id])}}"
                                   class="btn btn-info btn-xs edit"><i class="fa fa-edit"></i>
                                </a>

                                <a href="javascript:showModal('{{$row->id}}')"
                                   class="btn btn-danger btn-xs delete"><i class="fa fa-trash"></i>
                                </a>
                                @include('admin.elements.modal',['modal'=>'modalConfirmDelete', 'id' => $row->id,'url' => 'member/'.$row->id,'title'=>$row->title])
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="10">Không có kết quả
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
    </div>
@endsection